export const COLLEGE_LOGOS = {
  // --- THE "FIXED" MASCOT OVERRIDES ---
  "Iowa": "https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/Iowa_Hawkeyes_logo.svg/500px-Iowa_Hawkeyes_logo.svg.png", 
  "Miami": "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png",
  "Miami (FL)": "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png",
  "Miami FL": "https://a.espncdn.com/i/teamlogos/ncaa/500/2390.png",
  "Georgia State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2229.png",
  "Missouri": "https://a.espncdn.com/i/teamlogos/ncaa/500/142.png",
  "Mizzou": "https://a.espncdn.com/i/teamlogos/ncaa/500/142.png",

  // --- DARK MODE ENHANCEMENTS (White Outlines) ---
  "Arkansas": "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/8.png",
  "Kansas State": "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2306.png",
  "Kansas St": "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2306.png",
  "Indiana": "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/84.png",
  "IU": "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/84.png",
  "Oklahoma": "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/201.png",
  "OU": "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/201.png",
  "Penn State": "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/213.png",
  "Texas A&M": "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/245.png",

  // --- FULL ALPHABETICAL ROSTER (ZERO OMISSIONS) ---
  "Air Force": "https://a.espncdn.com/i/teamlogos/ncaa/500/2005.png",
  "Akron": "https://a.espncdn.com/i/teamlogos/ncaa/500/2006.png",
  "Alabama": "https://a.espncdn.com/i/teamlogos/ncaa/500/333.png",
  "Appalachian State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2026.png",
  "Arizona": "https://a.espncdn.com/i/teamlogos/ncaa/500/12.png",
  "Arizona State": "https://a.espncdn.com/i/teamlogos/ncaa/500/9.png",
  "Arkansas State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2032.png",
  "Army": "https://a.espncdn.com/i/teamlogos/ncaa/500/349.png",
  "Auburn": "https://a.espncdn.com/i/teamlogos/ncaa/500/2.png",
  "Ball State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2050.png",
  "Baylor": "https://a.espncdn.com/i/teamlogos/ncaa/500/239.png",
  "Boise State": "https://a.espncdn.com/i/teamlogos/ncaa/500/68.png",
  "Boston College": "https://a.espncdn.com/i/teamlogos/ncaa/500/103.png",
  "Bowling Green": "https://a.espncdn.com/i/teamlogos/ncaa/500/189.png",
  "Buffalo": "https://a.espncdn.com/i/teamlogos/ncaa/500/2084.png",
  "BYU": "https://a.espncdn.com/i/teamlogos/ncaa/500/252.png",
  "California": "https://a.espncdn.com/i/teamlogos/ncaa/500/25.png",
  "Central Michigan": "https://a.espncdn.com/i/teamlogos/ncaa/500/2117.png",
  "Charlotte": "https://a.espncdn.com/i/teamlogos/ncaa/500/2429.png",
  "Cincinnati": "https://a.espncdn.com/i/teamlogos/ncaa/500/2132.png",
  "Clemson": "https://a.espncdn.com/i/teamlogos/ncaa/500/228.png",
  "Coastal Carolina": "https://a.espncdn.com/i/teamlogos/ncaa/500/324.png",
  "Colorado": "https://a.espncdn.com/i/teamlogos/ncaa/500/38.png",
  "Colorado State": "https://a.espncdn.com/i/teamlogos/ncaa/500/36.png",
  "Duke": "https://a.espncdn.com/i/teamlogos/ncaa/500/150.png",
  "East Carolina": "https://a.espncdn.com/i/teamlogos/ncaa/500/151.png",
  "Eastern Michigan": "https://a.espncdn.com/i/teamlogos/ncaa/500/2199.png",
  "FAU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2226.png",
  "FIU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2229.png",
  "Florida": "https://a.espncdn.com/i/teamlogos/ncaa/500/57.png",
  "Florida State": "https://a.espncdn.com/i/teamlogos/ncaa/500/52.png",
  "Fresno State": "https://a.espncdn.com/i/teamlogos/ncaa/500/278.png",
  "Georgia": "https://a.espncdn.com/i/teamlogos/ncaa/500/61.png",
  "Georgia Southern": "https://a.espncdn.com/i/teamlogos/ncaa/500/290.png",
  "Georgia Tech": "https://a.espncdn.com/i/teamlogos/ncaa/500/59.png",
  "Hawaii": "https://a.espncdn.com/i/teamlogos/ncaa/500/62.png",
  "Houston": "https://a.espncdn.com/i/teamlogos/ncaa/500/248.png",
  "Illinois": "https://a.espncdn.com/i/teamlogos/ncaa/500/356.png",
  "Iowa State": "https://a.espncdn.com/i/teamlogos/ncaa/500/66.png",
  "Jacksonville State": "https://a.espncdn.com/i/teamlogos/ncaa/500/55.png",
  "James Madison": "https://a.espncdn.com/i/teamlogos/ncaa/500/256.png",
  "Kansas": "https://a.espncdn.com/i/teamlogos/ncaa/500/2300.png",
  "Kennesaw State": "https://a.espncdn.com/i/teamlogos/ncaa/500/338.png",
  "Kent State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2309.png",
  "Kentucky": "https://a.espncdn.com/i/teamlogos/ncaa/500/96.png",
  "Liberty": "https://a.espncdn.com/i/teamlogos/ncaa/500/2335.png",
  "Louisiana": "https://a.espncdn.com/i/teamlogos/ncaa/500/309.png",
  "Louisiana Tech": "https://a.espncdn.com/i/teamlogos/ncaa/500/2348.png",
  "Louisville": "https://a.espncdn.com/i/teamlogos/ncaa/500/97.png",
  "LSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/99.png",
  "Marshall": "https://a.espncdn.com/i/teamlogos/ncaa/500/276.png",
  "Maryland": "https://a.espncdn.com/i/teamlogos/ncaa/500/120.png",
  "Memphis": "https://a.espncdn.com/i/teamlogos/ncaa/500/235.png",
  "Michigan": "https://a.espncdn.com/i/teamlogos/ncaa/500/130.png",
  "Michigan State": "https://a.espncdn.com/i/teamlogos/ncaa/500/127.png",
  "Middle Tennessee": "https://a.espncdn.com/i/teamlogos/ncaa/500/2393.png",
  "Minnesota": "https://a.espncdn.com/i/teamlogos/ncaa/500/135.png",
  "Mississippi State": "https://a.espncdn.com/i/teamlogos/ncaa/500/344.png",
  "Navy": "https://a.espncdn.com/i/teamlogos/ncaa/500/2426.png",
  "NC State": "https://a.espncdn.com/i/teamlogos/ncaa/500/152.png",
  "Nebraska": "https://a.espncdn.com/i/teamlogos/ncaa/500/158.png",
  "Nevada": "https://a.espncdn.com/i/teamlogos/ncaa/500/2440.png",
  "New Mexico": "https://a.espncdn.com/i/teamlogos/ncaa/500/167.png",
  "New Mexico State": "https://a.espncdn.com/i/teamlogos/ncaa/500/166.png",
  "North Carolina": "https://a.espncdn.com/i/teamlogos/ncaa/500/153.png",
  "North Dakota State": "https://a.espncdn.com/i/teamlogos/ncaa/500/2449.png",
  "NDSU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2449.png",
  "North Texas": "https://a.espncdn.com/i/teamlogos/ncaa/500/249.png",
  "Northern Illinois": "https://a.espncdn.com/i/teamlogos/ncaa/500/2459.png",
  "Northwestern": "https://a.espncdn.com/i/teamlogos/ncaa/500/77.png",
  "Notre Dame": "https://a.espncdn.com/i/teamlogos/ncaa/500/87.png",
  "Ohio": "https://a.espncdn.com/i/teamlogos/ncaa/500/195.png",
  "Ohio State": "https://a.espncdn.com/i/teamlogos/ncaa/500/194.png",
  "Oklahoma State": "https://a.espncdn.com/i/teamlogos/ncaa/500/197.png",
  "Old Dominion": "https://a.espncdn.com/i/teamlogos/ncaa/500/295.png",
  "Ole Miss": "https://a.espncdn.com/i/teamlogos/ncaa/500/145.png",
  "Oregon": "https://a.espncdn.com/i/teamlogos/ncaa/500/2483.png",
  "Oregon State": "https://a.espncdn.com/i/teamlogos/ncaa/500/204.png",
  "Pitt": "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png",
  "Pittsburgh": "https://a.espncdn.com/i/teamlogos/ncaa/500/221.png",
  "Purdue": "https://a.espncdn.com/i/teamlogos/ncaa/500/2509.png",
  "Rice": "https://a.espncdn.com/i/teamlogos/ncaa/500/242.png",
  "Rutgers": "https://a.espncdn.com/i/teamlogos/ncaa/500/164.png",
  "Sam Houston": "https://a.espncdn.com/i/teamlogos/ncaa/500/2534.png",
  "San Diego State": "https://a.espncdn.com/i/teamlogos/ncaa/500/21.png",
  "San José State": "https://a.espncdn.com/i/teamlogos/ncaa/500/23.png",
  "SMU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2567.png",
  "South Alabama": "https://a.espncdn.com/i/teamlogos/ncaa/500/6.png",
  "South Carolina": "https://a.espncdn.com/i/teamlogos/ncaa/500/2579.png",
  "South Florida": "https://a.espncdn.com/i/teamlogos/ncaa/500/58.png",
  "USF": "https://a.espncdn.com/i/teamlogos/ncaa/500/58.png",
  "Southern Miss": "https://a.espncdn.com/i/teamlogos/ncaa/500/2572.png",
  "Stanford": "https://a.espncdn.com/i/teamlogos/ncaa/500/24.png",
  "Syracuse": "https://a.espncdn.com/i/teamlogos/ncaa/500/183.png",
  "TCU": "https://a.espncdn.com/i/teamlogos/ncaa/500/2628.png",
  "Temple": "https://a.espncdn.com/i/teamlogos/ncaa/500/218.png",
  "Tennessee": "https://a.espncdn.com/i/teamlogos/ncaa/500/2633.png",
  "Texas": "https://a.espncdn.com/i/teamlogos/ncaa/500/251.png",
  "Texas State": "https://a.espncdn.com/i/teamlogos/ncaa/500/326.png",
  "Texas Tech": "https://a.espncdn.com/i/teamlogos/ncaa/500/2641.png",
  "Toledo": "https://a.espncdn.com/i/teamlogos/ncaa/500/2649.png",
  "Troy": "https://a.espncdn.com/i/teamlogos/ncaa/500/2653.png",
  "Tulane": "https://a.espncdn.com/i/teamlogos/ncaa/500/2655.png",
  "Tulsa": "https://a.espncdn.com/i/teamlogos/ncaa/500/202.png",
  "UAB": "https://a.espncdn.com/i/teamlogos/ncaa/500/5.png",
  "UCF": "https://a.espncdn.com/i/teamlogos/ncaa/500/2116.png",
  "UCLA": "https://a.espncdn.com/i/teamlogos/ncaa/500/26.png",
  "UConn": "https://a.espncdn.com/i/teamlogos/ncaa/500/41.png",
  "UL Monroe": "https://a.espncdn.com/i/teamlogos/ncaa/500/2433.png",
  "UMass": "https://a.espncdn.com/i/teamlogos/ncaa/500/113.png",
  "UNLV": "https://a.espncdn.com/i/teamlogos/ncaa/500/2439.png",
  "USC": "https://a.espncdn.com/i/teamlogos/ncaa/500/30.png",
  "Utah": "https://a.espncdn.com/i/teamlogos/ncaa/500/254.png",
  "Utah State": "https://a.espncdn.com/i/teamlogos/ncaa/500/328.png",
  "UTEP": "https://a.espncdn.com/i/teamlogos/ncaa/500/2638.png",
  "UTSA": "https://a.espncdn.com/i/teamlogos/ncaa/500/2636.png",
  "Vanderbilt": "https://a.espncdn.com/i/teamlogos/ncaa/500/238.png",
  "Virginia": "https://a.espncdn.com/i/teamlogos/ncaa/500/258.png",
  "Virginia Tech": "https://a.espncdn.com/i/teamlogos/ncaa/500/259.png",
  "Wake Forest": "https://a.espncdn.com/i/teamlogos/ncaa/500/154.png",
  "Washington": "https://a.espncdn.com/i/teamlogos/ncaa/500/264.png",
  "Washington State": "https://a.espncdn.com/i/teamlogos/ncaa/500/265.png",
  "West Virginia": "https://a.espncdn.com/i/teamlogos/ncaa/500/277.png",
  "Western Kentucky": "https://a.espncdn.com/i/teamlogos/ncaa/500/98.png",
  "Western Michigan": "https://a.espncdn.com/i/teamlogos/ncaa/500/2711.png",
  "Wisconsin": "https://a.espncdn.com/i/teamlogos/ncaa/500/275.png",
  "Wyoming": "https://a.espncdn.com/i/teamlogos/ncaa/500/2751.png"
};