export const DRAFT_ORDER = [
  { "pick": 1, "teamKey": "LV", "info": "" },
  { "pick": 2, "teamKey": "NYJ", "info": "" },
  { "pick": 3, "teamKey": "ARI", "info": "" },
  { "pick": 4, "teamKey": "TEN", "info": "" },
  { "pick": 5, "teamKey": "NYG", "info": "" },
  { "pick": 6, "teamKey": "CLE", "info": "" },
  { "pick": 7, "teamKey": "WAS", "info": "" },
  { "pick": 8, "teamKey": "NO", "info": "" },
  { "pick": 9, "teamKey": "KC", "info": "" },
  { "pick": 10, "teamKey": "CIN", "info": "" },
  { "pick": 11, "teamKey": "MIA", "info": "" },
  { "pick": 12, "teamKey": "DAL", "info": "" },
  { "pick": 13, "teamKey": "LAR", "info": "from Falcons" },
  { "pick": 14, "teamKey": "BAL", "info": "" },
  { "pick": 15, "teamKey": "TB", "info": "" },
  { "pick": 16, "teamKey": "NYJ", "info": "from Colts" },
  { "pick": 17, "teamKey": "DET", "info": "" },
  { "pick": 18, "teamKey": "MIN", "info": "" },
  { "pick": 19, "teamKey": "CAR", "info": "" },
  { "pick": 20, "teamKey": "DAL", "info": "from Packers" },
  { "pick": 21, "teamKey": "PIT", "info": "" },
  { "pick": 22, "teamKey": "LAC", "info": "" },
  { "pick": 23, "teamKey": "PHI", "info": "" },
  { "pick": 24, "teamKey": "CLE", "info": "from Jaguars" },
  { "pick": 25, "teamKey": "CHI", "info": "" },
  { "pick": 26, "teamKey": "BUF", "info": "" },
  { "pick": 27, "teamKey": "SF", "info": "" },
  { "pick": 28, "teamKey": "HOU", "info": "" },
  { "pick": 29, "teamKey": "KC", "info": "from Rams" },
  { "pick": 30, "teamKey": "MIA", "info": "from Broncos" },
  { "pick": 31, "teamKey": "NE", "info": "" },
  { "pick": 32, "teamKey": "SEA", "info": "" },
  { "pick": 33, "teamKey": "NYJ", "info": "" },
  { "pick": 34, "teamKey": "ARI", "info": "" },
  { "pick": 35, "teamKey": "TEN", "info": "" },
  { "pick": 36, "teamKey": "LV", "info": "" },
  { "pick": 37, "teamKey": "NYG", "info": "" },
  { "pick": 38, "teamKey": "HOU", "info": "from Commanders" },
  { "pick": 39, "teamKey": "CLE", "info": "" },
  { "pick": 40, "teamKey": "KC", "info": "" },
  { "pick": 41, "teamKey": "CIN", "info": "" },
  { "pick": 42, "teamKey": "NO", "info": "" },
  { "pick": 43, "teamKey": "MIA", "info": "" },
  { "pick": 44, "teamKey": "NYJ", "info": "from Cowboys" },
  { "pick": 45, "teamKey": "BAL", "info": "" },
  { "pick": 46, "teamKey": "TB", "info": "" },
  { "pick": 47, "teamKey": "IND", "info": "" },
  { "pick": 48, "teamKey": "ATL", "info": "" },
  { "pick": 49, "teamKey": "MIN", "info": "" },
  { "pick": 50, "teamKey": "DET", "info": "" },
  { "pick": 51, "teamKey": "CAR", "info": "" },
  { "pick": 52, "teamKey": "GB", "info": "" },
  { "pick": 53, "teamKey": "PIT", "info": "" },
  { "pick": 54, "teamKey": "PHI", "info": "" },
  { "pick": 55, "teamKey": "LAC", "info": "" },
  { "pick": 56, "teamKey": "JAX", "info": "" },
  { "pick": 57, "teamKey": "CHI", "info": "" },
  { "pick": 58, "teamKey": "SF", "info": "" },
  { "pick": 59, "teamKey": "HOU", "info": "" },
  { "pick": 60, "teamKey": "CHI", "info": "from Bills" },
  { "pick": 61, "teamKey": "LAR", "info": "" },
  { "pick": 62, "teamKey": "DEN", "info": "" },
  { "pick": 63, "teamKey": "NE", "info": "" },
  { "pick": 64, "teamKey": "SEA", "info": "" },
  { "pick": 65, "teamKey": "ARI", "info": "" },
  { "pick": 66, "teamKey": "TEN", "info": "" },
  { "pick": 67, "teamKey": "LV", "info": "" },
  { "pick": 68, "teamKey": "PHI", "info": "from Jets" },
  { "pick": 69, "teamKey": "HOU", "info": "from Giants" },
  { "pick": 70, "teamKey": "CLE", "info": "" },
  { "pick": 71, "teamKey": "WAS", "info": "" },
  { "pick": 72, "teamKey": "CIN", "info": "" },
  { "pick": 73, "teamKey": "NO", "info": "" },
  { "pick": 74, "teamKey": "KC", "info": "" },
  { "pick": 75, "teamKey": "MIA", "info": "" },
  { "pick": 76, "teamKey": "PIT", "info": "from Cowboys" },
  { "pick": 77, "teamKey": "TB", "info": "" },
  { "pick": 78, "teamKey": "IND", "info": "" },
  { "pick": 79, "teamKey": "ATL", "info": "" },
  { "pick": 80, "teamKey": "BAL", "info": "" },
  { "pick": 81, "teamKey": "JAX", "info": "from Lions" },
  { "pick": 82, "teamKey": "MIN", "info": "" },
  { "pick": 83, "teamKey": "CAR", "info": "" },
  { "pick": 84, "teamKey": "GB", "info": "" },
  { "pick": 85, "teamKey": "PIT", "info": "" },
  { "pick": 86, "teamKey": "LAC", "info": "" },
  { "pick": 87, "teamKey": "MIA", "info": "from Eagles" },
  { "pick": 88, "teamKey": "JAX", "info": "" },
  { "pick": 89, "teamKey": "CHI", "info": "" },
  { "pick": 90, "teamKey": "MIA", "info": "from Texans" },
  { "pick": 91, "teamKey": "BUF", "info": "" },
  { "pick": 92, "teamKey": "DAL", "info": "from 49ers" },
  { "pick": 93, "teamKey": "LAR", "info": "" },
  { "pick": 94, "teamKey": "MIA", "info": "from Broncos" },
  { "pick": 95, "teamKey": "NE", "info": "" },
  { "pick": 96, "teamKey": "SEA", "info": "" },
  { "pick": 97, "teamKey": "MIN", "info": "Compensatory Selection" },
  { "pick": 98, "teamKey": "PHI", "info": "Compensatory Selection" },
  { "pick": 99, "teamKey": "PIT", "info": "Compensatory Selection" },
  { "pick": 100, "teamKey": "JAX", "info": "from Lions; Special Compensatory Selection" }
];